### ISSUE TITLE
Out of range ASCII

### ISSUE THREAD

**Issue by Wheatwizard** [DJMcMayhem/Brain-Flak#33]
When an ASCII flag is active and the output is out of the ASCII range (e.g. negative) a nasty ruby error is thrown.  Ideally this will change but the question is how.  We could create a custom Brain-Flak error or we could implement a wraparound (i.e. mod 256 the output before conversion).

**Comment by DJMcMayhem** [comment]
What if we extended ASCII mode to unicode characters? That still brings up the point of what to do with negative characters and characters above 65535. It seems like the most sensible thing would be to just take modulo 65536.

I suppose the other option would be to just silently ignore characters outside of ASCII.

**Comment by 1000000000** [comment]
I think extending ASCII mode to unicode would be a good idea since Brain-Flak can already handle unicode strings as input and I agree that modulo at the end would be probably most sensible as well.

**Comment by Wheatwizard** [comment]
I believe that we should drop support for unicode as input and have ASCII only for both input and output.

**Comment by 1000000000** [comment]
I like the idea of ASCII only being the default mode (error on non-ascii input), but having a flag to enable unicode support. My only remaining question is do we want to use ascii which is 7-bit (128 characters) or do we want to use one of the [many 8 bit extensions](https://en.wikipedia.org/wiki/Extended_ASCII)? The only reason I would consider the 8 bit extensions is because I like 256 more than 128.
