### ISSUE TITLE
Stable Releases

### ISSUE THREAD

**Issue by Wheatwizard** [DJMcMayhem/Brain-Flak#36]
Based on the release of the ASCII mode  I thought it might be a good idea to use Github's "releases" feature to differentiate between stable and non-stable versions.  As well as having proper version numbers (e.g. 1.0.9).

**Comment by 1000000000** [comment]
Sounds good. Milestones + issues can help us keep track of when we will be creating a release. Also a latest-release branch that only gets updated when we have a stable release might be a good idea so that when we are ready for a release a pull request to that branch can be created so everyone can review the changes and do one check for bugs before a release is created.

**Comment by DJMcMayhem** [comment]
+1, sounds good to me. We should also add a `-v` flag that prints the current version to STDERR. That way, running debug on TIO you can see the current version. Which release do you think would be best for a V1?

**Comment by 1000000000** [comment]
I think the next release should be V1 since the last two groups of big updates did a lot to make Brain-Flak whole and now most of the bugs have been fixed. There are still a few bugs I'd like to see squashed and a few minor features to add, but besides that everything feels very complete.

A tentative list of things I'd like before the next release:
- Features
  - Ability to take ASCII input from command line arguments #40 
  - Help command line flag #39 
  - Version command line flag #39 
  - Create new and/or modify existing debug flags for ASCII #38 
- Bugs
  - ASCII out of range #33 
  - Unclosed braces don't error #37 

It is late so there are some I am forgetting or maybe there are some that I did not think of. Regardless, these are all pretty minor so I'd say we are definitely looking at the home stretch to the place where we should have a release.

**Comment by 1000000000** [comment]
I have created a milestone [Version 1.0.0](https://github.com/DJMcMayhem/Brain-Flak/milestone/1) and created and added issues for all the changes I mentioned above that didn't already have issues. I put a due date on the milestone because @Wheatwizard and I would like to get these changes wrapped up pretty soon.

Is there anything else that needs to be said or is this issue ready to be closed?

**Comment by 1000000000** [comment]
It seems like this issue is about wrapped up
