### ISSUE TITLE
Unclosed Brackets do not generate an error

### ISSUE THREAD

**Issue by Wheatwizard** [DJMcMayhem/Brain-Flak#37]
As of commit 731da210604e03e9943cdf6c4915203e1ef01a77 unclosed brackets no longer generate an error.  The program runs in entirety as if the unclosed brackets were not there.

**Comment by CatsAreFluffy** [comment]
This behavior sounds useful for writing programs. Request to be readded (possibly requiring the use of a flag).

**Comment by DJMcMayhem** [comment]
No. It goes against the whole point of the language. It might make brain-flak programs shorter in general, but they would no longer be brain-flak programs, since the whole point of the language is the matching bracket restriction.

I would consider brain-flak with implicitly closing brackets to be a variant of the language.

**Comment by CatsAreFluffy** [comment]
Implicitly closing? What? Brackets don't have to close (except {}) if you
use the Third Stack interpretation!

**Comment by Wheatwizard** [comment]
It seems we are in agreement. I am going to implement compile time brace checking.
