### ISSUE TITLE
Brain-Flak Organization

### ISSUE THREAD

**Issue by 1000000000** [DJMcMayhem/Brain-Flak#43]
There are currently three repositories on GitHub associated with Brain-Flak (that I know of) distributed across the same number of users. From an organization perspective I was thinking it might be a good idea to create a Brain-Flak organization and migrate all these repositories to that organization.

**Comment by DJMcMayhem** [comment]
I see [6 repositories across 4 users](https://github.com/search?utf8=%E2%9C%93&q=brain-flak) Personally I think this isn't a great idea for a couple different reasons.
- If someone wants to make their own brain-flak interpreter, they're totally free to do so. (Especially since it's MIT). If they do, I don't want to force them to join an organization and then taking over their repository. 
- Most of the brain-flak related repositories are unofficial. Technically, I think this is the only _official_ repository, and that's just because it happens to be the first (and most well known). 
- Since it's a pretty simple language to implement, I know some people are writing it just for fun/to learn a language better. That's why I initially wrote it in ruby, and why [this one](https://github.com/vihanb/Brain-Flak-CPP) is in C++. 
- It's not important enough to warrant having an organization. It's a great language and all, and I'm really happy with how it turned out, but it's still just an esoteric language. Nobody's going to write serious software in it, and development is pretty much done. That's not to say I don't want to encourage people to use it, especially since I think it's a blast,

**Comment by Wheatwizard** [comment]
I've thought this over and while both of you bring up good points I think I agree with DJMcMayhem on this one.

**Comment by DJMcMayhem** [comment]
@Wheatwizard I'm glad to hear that, but I actually did end up going ahead an making a [brain-flak organization](https://github.com/Brain-Flak), but this was mostly because I wanted to start on an online interpreter/visualizer, and I thought `brain-flak.github.io` sounded better than `DJMcmayhem.github.io/brian-flak`

**Comment by 1000000000** [comment]
Will the Brain-Flak repository be migrated to that organization?

**Comment by DJMcMayhem** [comment]
@1000000000 I'm not sure. I don't particularly care either way, so unless you or Wheatwizard strongly think I should I probably won't bother.

**Comment by DJMcMayhem** [comment]
I'm going to close this since there is now an organization, although I'm not planning on migrating any repositories.
