### ISSUE TITLE
Multiply example hangs if second input is not provided

### ISSUE THREAD

**Issue by DJMcMayhem** [DJMcMayhem/Brain-Flak#5]
This brain-flak code hits an infinite loop:

```
({}<>)<>({}[]){({}[])<>(({}))<>}<>{({}<>{})<>}<>
```

when the input is `3`. Strangely enough, if I give the second input as `0`, it does _not_ hang. I did not expect this behavior since an empty stack should pop a 0, so they should behave identically.

**Comment by DJMcMayhem** [comment]
I'm not _exactly_ sure what causes this, so I'm going to add some debug output to brain-flak itself. I don't know what that will look like, but it will probably be a CLI flag (probably `-d`) and some commands to display
- The active stack
- A specific stack
- The result of a function call

and a way to pause for user input, as well as maybe some others.

**Comment by 1000000000** [comment]
Not sure if it will be useful but earlier today I refactored the program so that it is contained in a class. The class still needs some work with getters and setters. It is pushed on the debug-dev branch.

Edit: wow lots of activity today. The debug-dev branch does not have the changes from @Wheatwizard's changes. I will try to fix that. Also created issue #6 for further discussion on the subject of the debugger.

**Comment by Wheatwizard** [comment]
I found the issue.  You subtract one from the bottom number because you already start with one copy of the top number.  When this is zero or not provided it will put -1 on the stack.  Since you subtract to reach zero you will never reach zero.  This can be fixed by removing the `({}[])` (subtracts 1) before duplication, and adding `{}` (pops 1) after duplication.  Going from `({}<>)<>({}[]){({}[])<>(({}))<>}<>{({}<>{})<>}<>` to `({}<>)<>{({}[])<>(({}))<>}<>{}{({}<>{})<>}<>`.  This also has the added benefit of making the program shorter.  This was not a problem with the implementation but rather the example code. I have a pull request that does this (and a little more).

**Comment by DJMcMayhem** [comment]
Hmm, okay. I bet some of this issue would have been avoided if numbers wrapped at some point. +127/-128? +65535/-65536? Although that would instead just produce the wrong value instead of looping forever. I wonder if we should change one of the functions to something supporting negative numbers better. How useful is the `<>` dilad? I bet it would be really useful somewhere, but I haven't used in a program yet. (Although I haven't written very many brain-flak program overall)

**Comment by Wheatwizard** [comment]
In my opinion the `<>` is very useful.  Without it it would be very difficult to move data around.  For example `({}<><({}<>)>)` swaps the top two items on the current stack and `{({}<>)<>}<>({}<>)({}<<>{({}<>)<>}<>>)` moves the bottom item to the top of the stack.  Both of these would become very difficult if it was not for the `<>` dilad.  The way I typically use it is to write something like `({}<foo>)` which allows us to pick up the top item in the stack perform some operation `foo` and then put the item back on top of the stack.  In my opinion the least useful is the `[]` dilad.  I find, and perhaps this is just me, that I almost always just want to run some code and print the active stack at the end.  It should be possible to print out anything without using the `[]` dilad.  However I like @DJMcMayhem have only written a couple dozen programs and this might be a symptom of personal style.

**Comment by Wheatwizard** [comment]
If you want better support for negative numbers I would suggest repurposing the `[]` nilad to become a sign flip operator.  e.g.  `(()()()[])` pushes negative 3 to the stack.  The old `[]` could be replaced by the snippet `<(()[])>{}` and it might be easier to deal with negative numbers. This is just an idea I had I don't know if it is a particularly good one.

**Comment by DJMcMayhem** [comment]
I'm not sure if that's a good idea since decrement is such a common operation, it would be nice to keep it short. It would make more sense to repurpose the `[]` dilad, e.g. `([()()()])` would push negative 3. We can talk more about design here: http://chat.stackexchange.com/rooms/41599/brain-flak

**Comment by Wheatwizard** [comment]
Unfortunately I do not have sufficient reputation to talk in a stack exchange chat room, so I will try to just say one thing here first.  If you intend to repurpose functions it might be a good idea to implement some way of determining where the end of a stack is.  Currently it is impossible to write a program that can do something as simple as sum all of the inputs.  This is because the `{}` dilad cannot tell the difference between a zero and the end of the stack.  Thus by putting enough zeros in between two inputs you can always trick an algorithm into thinking that it has reached the bottom of the stack and prematurely terminating.  e.g.  the code `{({}<>)({}{})<>}<>` will work for a sequence like `8 3 7 14` but will fail on `1 0 2` (outputting `1` instead of `3`).  you could make it more sophisticated by moving more inputs at a time (e.g. `{({}{}<>)({}{})<>}<>` or even `{({}{}{}<>)({}{})<>}<>`) but all of these will eventually fail if given enough zeros (`1002` or `10002`).  This presents a pretty large problem for anyone writing in brainflak and may even effect the completeness of the language.  I currently do not mind to much the negative situation but I do find this to be particularly concerning.

**Comment by DJMcMayhem** [comment]
@Wheatwizard You know, I'm not sure if that's too much of a big deal. This is, afterall `An esolang designed to be painful to use`. And, there are certainly ways to get around this. For example, to sum `1 0 2`, provide a third argument, e.g. the number of inputs. So the full input would be `1 0 2 3` (Since there are three inputs), and this can be summed with `({}<>){({}[])<>({}{})<>}<>`. An additional input is not that unreasonable. This is even necessary in more convenient languages, such as C which also has no concept of array length. (If the array is an argument to a function) Also, that may be the only time I've ever referred to C as a "More convenient language", haha. 

However, it might be worth considering a "Stack length" monad. The only problem with that is that I like all of the current monads, and I don't really want to add additional bracket types. I really like the minimalism of every program being a matched set of brackets.

**Comment by DJMcMayhem** [comment]
I suppose if we changed the `[]` dilad to "negative", than we wouldn't really need the `[]` monad anymore since the same thing could be achieved with `[()]`. Then we could repurpose the `[]` dilad to "Current Stack Height"

**Comment by DJMcMayhem** [comment]
After merging Pull Request #9, this issue seems to be fixed, so I'm closing the issue.

**Comment by Wheatwizard** [comment]
I very much like the idea changing the `[]` dilad and monad.  I think it is a very elegant solution to the problem.  It will have very little affect on current programs (the few that are) and make a whole new realm of things possible with brainflak.
